name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC (한국시간 오전 9시)
  workflow_dispatch:      # 수동 실행도 가능하게 허용

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Git 사용자 정보 설정
      - name: Set up Git
        run: |
          git config user.name "hyeondorii"
          git config user.email "gbdqbd123@gmail.com"

      # 3. 매일 바뀌는 내용 만들기 (date.txt에 timestamp 넣기)
      - name: Update date file with timestamp
        run: |
          echo "Last commit: $(date -u '+%Y-%m-%dT%H:%M:%S.%3NZ')" > date.txt

      # 4. 변경사항 커밋 & 푸시 (잔디 자라게!)
      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add date.txt
          git commit -m "chore: daily auto commit $(date -u '+%Y-%m-%d')" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
